# Generated by Django 3.2.24 on 2025-05-05 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
