# Generated by Django 3.2.24 on 2025-05-21 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graduation', '0002_add_question_field_and_alter_attempt_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_keywords',
            field=models.JSONField(),
        ),
    ]
